### PR TITLE
feat(role): add homepage

### PR DESCRIPTION
**Pull request by JigSawFr**
# Description
A modern (fully static, fast), secure (fully proxied), highly customizable application dashboard with integrations for more than 25 services and translations for over 15 languages. Easily configured via YAML files (or discovery via docker labels).

- **Github Repository:** https://github.com/benphelps/homepage
- **Documentation:** https://gethomepage.dev/

# How Has This Been Tested?

- [x] App is working as expected. (_Container is alive and answering to requests_)
- [x] App use a dedicated folder in `/opt` directory.
- [x] App secured by Authelia SSO authentication system.
- [x] A subdomain is correctly created for the web-ui. (_via Cloudflare_)
- [x] Custom TimeZone is set to the container and application.
- [x] Custom UID/GID is set to the container to run under Saltbox user.
- [ ] Healthcheck is added to the container.
- [x] Custom volumes are mounted for advanced usage (icons, images)
- [ ] ~~Sub-role was added (docker socket proxy) for security and run this container without root.~~
- [x] Default config files with plenty of examples. 

# Traefik Widget
~~At this time, homepage container is unable to reach traefik endpoint locally,
You need to add temporary these lines in your inventory file:~~
```
traefik_docker_labels_custom:
  traefik.http.routers.traefik-local.rule: "Host(`traefik`)"
  traefik.http.routers.traefik-local.entrypoints: "web, websecure"
  traefik.http.routers.traefik-local.service: "api@internal"
```
~~And your traefik widget will work as expected !~~
A PR is closed: https://github.com/saltyorg/Saltbox/pull/115

# Healthcheck
If you want healthcheck for this container, add these lines to your inventory:
```
homepage_docker_healthcheck:
  test: ["CMD", "wget", "--spider", "http://localhost:{{ homepage_web_port }}"]
  interval: 1m
  timeout: 10s
  retries: 2
  start_period: 30s
```

### CODE REVIEW

**Comment by maximuskowalski** [comment]
There is already a docker socket proxy role in saltbox FYI
https://github.com/saltyorg/Saltbox/tree/master/roles/docker_socket_proxy

Can see it used in the glances web role here in sandbox
https://github.com/saltyorg/Sandbox/blob/5bcd35d41ebe8abfc35cdd70289e1bc1ea15136e/roles/glances_web/tasks/main.yml#L16

**Comment by JigSawFr** [comment]
Discussion in #sandbox-dev, original role is not instances ready nor customizable

**Comment by JigSawFr** [comment]
Moved enhancement of docker-socket-proxy role to Saltbox core https://github.com/saltyorg/Saltbox/pull/116

**Comment by owine** [comment]
With the docker-socket-proxy change merged to master, probably need a update to match the style here:

https://github.com/saltyorg/Saltbox/commit/37ccde8ce97923ed7f65aeb213720ae3669c1930

**Comment by JigSawFr** [comment]
> With the docker-socket-proxy change merged to master, probably need a update to match the style here:
> 
> 
> 
> https://github.com/saltyorg/Saltbox/commit/37ccde8ce97923ed7f65aeb213720ae3669c1930

Exactly, was editing before final merge in case of change in salt box ;) will change this asap

**Pull request merged**
