### PR TITLE
Update for Recyclarr rootless container

### PR DESCRIPTION
**Pull request by BeansIsFat**
# Description

Remove PUID/PGID from role as Recyclarr has switched to a rootless container and these envs will break new installs.

# How Has This Been Tested?

Tested on my production server using the `edge` tag for Recyclarr. Confirmed it's working with `latest` tag now that it's been released.

### CODE REVIEW

**Comment by saltydk** [comment]
Breaking it? If he stopped using those ENVs it would just silently do nothing.

**Comment by saltydk** [comment]
Also, wouldn't you need to pass the user to the container then, this isn't enough of a change.

**Comment by saltydk** [comment]
This change doesn't seem to be in latest either.

**Comment by BeansIsFat** [comment]
> Breaking it? If he stopped using those ENVs it would just silently do nothing.

He added checks for those ENVs and throws an error if either one is present. See https://github.com/recyclarr/recyclarr/blob/master/docker/scripts/prod/entrypoint.sh

> Also, wouldn't you need to pass the user to the container then, this isn't enough of a change.

You're right. I need to add `recyclarr_docker_user: "{{ uid }}:{{ gid }}"`.

> This change doesn't seem to be in latest either.

It's in the `master` branch but the image hasn't been pushed to the `latest` docker tag yet. Was getting ahead of myself by creating the draft PR and mentioning the final test I was going to do before marking it Ready.

I'll close this draft, make the changes, test it, and wait for the release.

**Comment by saltydk** [comment]
It is fine to leave this as a draft, just make sure to include all the relevant changes and we'll merge it when it gets pushed to latest.

**Pull request merged**
