### PR TITLE
Role added for Unifi Controller

### PR DESCRIPTION
**Pull request by grostim**

### CODE REVIEW

**Comment by maximuskowalski** [comment]
Have you tested this role - I am unable to test without hardware?
Do the commented out lines in ports need to stay? Perhaps they are meant to be added as needed via inventory?
`unifi_docker_ports_custom:` Should these all be default ports?

**Comment by grostim** [comment]
> Have you tested this role - I am unable to test without hardware? 
Yes.

> Do the commented out lines in ports need to stay? Perhaps they are meant to be added as needed via inventory? `unifi_docker_ports_custom:` Should these all be default ports?

As far as i know the only port for which a direct access is mandatory is 8080 . (and 8433 if there is no reverse proxying)
The other ones are optional and depend on the user usecase.
I kept the comments for references, but yes, we could make it prettier by making them addesdon demand from inventory or settings.

**Comment by grostim** [comment]
> > Have you tested this role - I am unable to test without hardware?
> 
> Yes.
> 
> > Do the commented out lines in ports need to stay? Perhaps they are meant to be added as needed via inventory? `unifi_docker_ports_custom:` Should these all be default ports?
> 
> As far as i know the only port for which a direct access is mandatory is 8080 . (and 8433 if there is no reverse proxying) The other ones are optional and depend on the user usecase. I kept the comments for references, but yes, we could make it prettier by making them added on demand from inventory or settings.
> 
> If you have a sample role from which i may take example to do the same for unifi, i will be happy to do it.

reply to myself: The plex container looks like a good basis.

**Comment by grostim** [comment]
> > > > Have you tested this role - I am unable to test without hardware?
> > > 
> > > 
> > > Yes.
> > > > Do the commented out lines in ports need to stay? Perhaps they are meant to be added as needed via inventory? `unifi_docker_ports_custom:` Should these all be default ports?
> > > 
> > > 
> > > As far as i know the only port for which a direct access is mandatory is 8080 . (and 8433 if there is no reverse proxying) The other ones are optional and depend on the user usecase. I kept the comments for references, but yes, we could make it prettier by making them added on demand from inventory or settings.
> > > If you have a sample role from which i may take example to do the same for unifi, i will be happy to do it.
> > 
> > 
> > reply to myself: The plex container looks like a good basis.
> 
> Plex is actually outdated in some ways. Radarr/Sonarr have the format we'll be using for the most part.

I understand that radarr/sonarr have everything you need to deal with multiple instances, but i don't think we need that for unifi.

Is there somethinh you would improve in my latest commit ?

**Comment by owine** [comment]
I think ports 3478 and 10001 are needed by default.

**Comment by maximuskowalski** [comment]
> I think ports 3478 and 10001 are needed by default.

Will check the cloudbox role maybe, been a while.

**Comment by maximuskowalski** [comment]
https://github.com/Cloudbox/Community/blob/049d1cfc8389a15153ca8918636a4eee93366a48/roles/unifi/tasks/main.yml#L37

The idiot that wrote that role has
```
    published_ports:
      - 3478:3478/udp
      - "{{ unifi.port|default('8089',true) }}:8080"
```

**Comment by maximuskowalski** [comment]
From LSIO docs we have
```
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
      ```
      So I guess we need all the non optional ones? - I'll add them and push this through and wait for someone to report either way.
      
   Thanks for doing documentation, really helps a lot.

**Pull request merged**
