### PR TITLE
Loki and Promtail

### PR DESCRIPTION
**Pull request by jolbol1**
# Description

Adds Loki https://grafana.com/oss/loki/
Adds promtial https://grafana.com/docs/loki/latest/clients/promtail/

This allows for log visualisation and aggregation on grafana.

I used these configs, and have provided them as templates: 
https://github.com/jolbol1/loki-promtail-configs/blob/main/loki-config.yml
https://github.com/jolbol1/loki-promtail-configs/blob/main/promtail-config.yml

In order for docker logs to be tagged, you need the following:
`--log-driver json-file --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"` on every container.

I have [submitted a PR](https://github.com/saltyorg/Saltbox/pull/68) to Saltbox that would allow you to set this a a global, or per role variable like so:
Globally in localhost.yml
```
docker_log_driver: "json-file"
docker_log_options: "{% raw %}tag='{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'{% endraw %}"
```
or per role:
```
plex_log_driver: "json-file"
plex_log_options: "{% raw %}tag='{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'{% endraw %}"
```

I got these options from the recommended set up here: https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460

Lastly, Salty as you mentioned you will be taking a look at this yourself. I decided to post this here anyways as I already gave it a go and maybe we would go about it in the same ways. 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.

- [x] modified saltbox server with sandbox [(see saltbox PR)](https://github.com/saltyorg/Saltbox/pull/68)
- [x] Default SB install and sandbox
- [x] Fresh server install

### CODE REVIEW

**Comment by saltydk** [comment]
Haven't forgotten to look at this and my own stuff but focus is on 22.04 testing at the moment. Will get back to it soon.

**Comment by saltydk** [comment]
Apologies for the wait, it is still on the todo list, just letting you know that I haven't forgotten.

**Comment by jolbol1** [comment]
> Apologies for the wait, it is still on the todo list, just letting you know that I haven't forgotten.

No worries, also pretty busy so haven't had time to check in with this!

**Comment by maximuskowalski** [comment]
@jolbol1 Do you want to think about just going ahead with this now, Salty is unlikely to have time to look at this any time soon.

**Comment by jolbol1** [comment]
> @jolbol1 Do you want to think about just going ahead with this now, Salty is unlikely to have time to look at this any time soon.

Apologies, I have also been busy. No longer use saltbox so closing the PR as I wont be able to add anything more.

**Comment by saltydk** [comment]
Thanks for the reply :)

**Pull request closed without merging**
