### PR TITLE
Add Private Bin

### PR DESCRIPTION
**Pull request by tipdec-siblyn**
# Description
PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data.
It's privacy-preserving and encrypted-by-default.
Project: https://privatebin.info/
Container: https://hub.docker.com/r/privatebin/nginx-fpm-alpine
Wiki: https://github.com/PrivateBin/PrivateBin/wiki

# How Has This Been Tested?

I have tested it on my saltbox setup multiple time (delete + install) and everything work without issues.
It's my first role, so tell me if something is not correct.
Thanks
- [ ✅] ```sb install sandbox-privatebin```
- [ ✅] Check that the service work at privatebin.domain.com

### CODE REVIEW

**Comment by chazlarson** [comment]
Are you creating documentation for this role?

Also, the intention here is that you change these to reflect the testing steps you took, not leave them as-is.
image

**Comment by tipdec-siblyn** [comment]
For the document, I think the description is enough, it's a very simple app. 
I have updated the testing steps.

**Comment by keldian** [comment]
Is the intention for this to be accessible to anyone with the url? Because you didn't include SSO middleware (Authelia), and there's no built-in auth options to my understanding.

**Comment by chazlarson** [comment]
> For the documentation, I think the description is enough, it's a very simple app. I have updated the testing steps.

Right, but am I expected to create that documentation page or are you going to do it as part of creating the role?  You're creating the role, have presumably used it and are presumably familiar with any setup steps that need to be done after running the tag.

**Comment by thatsnasty** [comment]
> Is the intention for this to be accessible to anyone with the url? Because you didn't include SSO middleware (Authelia), and there's no built-in auth options to my understanding.

For this to work as intended you shouldn't use any type of auth. The individual pastes can be password protected if needed. Of course this does leave it open to abuse, but that's rare.

**Comment by thatsnasty** [comment]
Salty recommended using [this image] (https://hub.docker.com/r/jgeusebroek/privatebin/) [here](https://discord.com/channels/853755447970758686/944260106852368384/951243053786619974) when I was it adding to Saltbox manually

**Comment by tipdec-siblyn** [comment]
> For this to work as intended you shouldn't use any type of auth. The individual pastes can be password protected if needed. Of course this does leave it open to abuse, but that's rare.

Yes the goal is to create bin and share it with others (with or without password)

**Comment by tipdec-siblyn** [comment]
> Salty recommended using [this image](https://hub.docker.com/r/jgeusebroek/privatebin/), [here](https://discord.com/channels/853755447970758686/944260106852368384/951243053786619974) when I was it adding to Saltbox manually

Nice I didn’t know this one, do you need to specify the two volumes path?

**Comment by tipdec-siblyn** [comment]
> > For the documentation, I think the description is enough, it's a very simple app. I have updated the testing steps.
> 
> Right, but it would be appreciated if you would create that page as part of creating the role. You're creating the role, have presumably used the thing and are presumably familiar with any setup steps that need to be done after running the tag. I haven't and would have to research all that.

So I need to create a pull in the doc repo ?

**Comment by maximuskowalski** [comment]
Any plan to switch the image or just going to stick with this one?

**Comment by tipdec-siblyn** [comment]
> Any plan to switch the image or just going to stick with this one?

I'm working on it actually, with the help of thatnasty who have a working setup of it

**Comment by maximuskowalski** [comment]
No problem at all - I will hold off on merging it then.

**Comment by tipdec-siblyn** [comment]
I have prepared as well the doc request but I wait to get working the image ;)

**Comment by tipdec-siblyn** [comment]
All good?

**Review by maximuskowalski — APPROVED** [review]
If you are finished I am happy to merge.

**Comment by tipdec-siblyn** [comment]
> 

Yes I have finish thanks

**Pull request merged**
