### PR TITLE
Role/traefik robotstxt

### PR DESCRIPTION
**Pull request by JigSawFr**
# Description

This project implements a small(5.7 KB) and lightweight http-server, just serving a disallow-robots.txt file using the Zig programming language(https://ziglang.org/).

Cf. https://github.com/mstroecker/zig-robotstxt

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.

- [x] Production test performed

### CODE REVIEW

**Comment by JigSawFr** [comment]
Tag working as expected and production test performed.

```
Friday 15 April 2022  09:23:56 +0200 (0:00:03.844)       0:00:15.087 **********
===============================================================================
traefik_robotstxt : Resources | Tasks | Docker | Create Docker Container | Create Docker Container -------------------------------------------------------------------------------------------------------- 3.84s
sanity_check : Repository | Print Current Hash ------------------------------------------------------------------------------------------------------------------------------------------------------------ 2.42s
sanity_check : Get all available tags --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.34s
traefik_robotstxt : Resources | Tasks | Docker | Remove Docker Container | Remove Docker Container -------------------------------------------------------------------------------------------------------- 1.94s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.71s
pre_tasks : APT | Remove APT locks ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.63s
sanity_check : Find Ansible version ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.35s
sanity_check : Check if 'saltbox' folder is present ------------------------------------------------------------------------------------------------------------------------------------------------------- 0.33s
sanity_check : Repository | Check Current Hash ------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.19s
sanity_check : Check if 'backup.lock' is present in the 'saltbox' folder ---------------------------------------------------------------------------------------------------------------------------------- 0.18s
traefik_robotstxt : Create Docker container --------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.09s
traefik_robotstxt : Remove existing Docker container ------------------------------------------------------------------------------------------------------------------------------------------------------ 0.09s
sanity_check : Delete stale 'backup.lock' ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.07s
sanity_check : List available tags ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.07s
sanity_check : Fail when 'backup.lock' exists. ------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.06s
sanity_check : Upgrade Ansible | Exit --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
traefik_robotstxt : Resources | Tasks | Docker | Remove Docker Container | Set '_var_prefix' variable ----------------------------------------------------------------------------------------------------- 0.05s
sanity_check : Ensure valid tags were provided. ----------------------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
sanity_check : Check if Ansible needs upgrading ----------------------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
traefik_robotstxt : Resources | Tasks | Docker | Create Docker Container | Set '_var_prefix' variable ----------------------------------------------------------------------------------------------------- 0.05s
```

**Comment by JigSawFr** [comment]
Need to get ride of default traefik middlewars to work as expected.

**Comment by JigSawFr** [comment]
@saltydk / @maximuskowalski PR is now ready and functional ! Thanks for you help :)

**Comment by saltydk** [comment]
you can revert the combine order again so it is like normal as that didn't make a difference

**Comment by JigSawFr** [comment]
@saltydk done ;)

**Comment by saltydk** [comment]
combine isn't wrapped around the first entry :p

**Comment by JigSawFr** [comment]
Et voilà !

**Review by maximuskowalski — APPROVED** [review]
One small fix with a final line, will merge after CI has done its thing.

**Pull request merged**
