### PR TITLE
upgrade postgres

### PR DESCRIPTION
**Pull request by balogan**
# Description

For new roles please include a brief description of what this app does, or what the purpose of this role is. Include a link to the docker container used, the projects home page and a link to the documentation if it exists.

It would be greatly appreciated if you create a sandbox documentation page yourself and do a PR into the [docs repo](https://github.com/saltyorg/docs).  You, as the person creating the role, have presumably used the thing and are presumably familiar with any setup steps required.  Anyone else here would need to research that.

For existing roles, please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.  You can use the checkboxes below or delete them as you wish.

- [ ] This is not a test I performed
- [ ] I did not read the paragraph above this before checking this box
- [ ] I have now checked three boxes without reading any of the text
- [ ] I have decided to leave these meaningless checkboxes in my pull request as a demonstration that I did not read to the end.

Please do not leave those four checkboxes in your pull request without editing their contents.

### CODE REVIEW

**Comment by owine** [comment]
This will break existing installs

**Comment by balogan** [comment]
> This will break existing installs

Are there any mechanisms in place for  upgrading?

**Comment by owine** [comment]
> > This will break existing installs
> 
> Are there any mechanisms in place for upgrading?

Postgres does not support in place upgrades gracefully with the docker container. It typically requires a dump of the database and importing into a fresh instance on the new version. There are some unofficial containers that do some workarounds on this but it’s a postgres design decision/limitation in docker.

**Comment by balogan** [comment]
As a workaround is there a way to check for existing installs and condition off that?

**Comment by owine** [comment]
Would have to check for existing Postgres appdata, check the PG_VERSION file against the desired version and take steps to dump/import if needed

**Comment by owine** [comment]
I am going to close this PR. I will be pushing a change to roles that deploy postgres databases that exposes the docker image and tag as inventory variables so the user can use alternative images/tags if they are comfortable executing the upgrade steps on their own.

**Pull request closed without merging**
