### PR TITLE
Omegabrr

### PR DESCRIPTION
**Pull request by keldian**
Syncs titles from Radarr and Sonarr libraries to Autobrr filters.

# How Has This Been Tested?

Deployed on prod server saltbox_mod then regular sandbox.

### CODE REVIEW

**Comment by saltydk** [comment]
This looks a bit messy in regards to the instances. I'd look at notifiarr for inspiration.

**Comment by keldian** [comment]
Notifiarr was my starting point actually. Not sure what you're referring to as being messy, specifically.

**Comment by saltydk** [comment]
you copied stuff from the resource role instead of using it.

**Comment by saltydk** [comment]
Additionally the autobrr import is not needed and will override any inventory overrides when done this way. The reason it is not needed it a new addition though so not surprising you don't know about it yet.

**Comment by keldian** [comment]
> you copied stuff from the resource role instead of using it.

I did that because it contains Lidarr and Readarr tasks which aren't relevant to this app and gave the playbook a longer run time. Do I flip that back then?

**Comment by saltydk** [comment]
Yes otherwise you won't get fixes that I may have to make down the road and makes maintaining this more annoying

**Comment by keldian** [comment]
Autobrr import was needed on saltbox_mod–I hadn't thought to do that test after the move to sandbox. I guess that's an important difference between sandbox and mod. 👍

**Comment by saltydk** [comment]
I can make that not be a thing later.

**Comment by saltydk** [comment]
> I can make that not be a thing later.

https://github.com/saltyorg/Saltbox/commit/7035b1f557f3bce76bfaf9b191bf8d3d92e5d85e

**Pull request merged**
