### PR TITLE
Add Tauticord Role

### PR DESCRIPTION
**Pull request by benwaco**
Requries configuration via `config/config.yaml`

# Description

https://github.com/nwithan8/tauticord

Will update docs if merged.

# How Has This Been Tested?

Tested on my server with my Plex server.

### CODE REVIEW

**Comment by maximuskowalski** [comment]
Edited some minor formatting but you also need to edit sandbox.yml to include the role. How did you test it without editing this file?
https://github.com/saltyorg/Sandbox/blob/master/sandbox.yml

See the examples there - fairly straightforward to include it.

**Comment by benwaco** [comment]
> Edited some minor formatting but you also need to edit sandbox.yml to include the role. How did you test it without editing this file? https://github.com/saltyorg/Sandbox/blob/master/sandbox.yml
> 
> See the examples there - fairly straightforward to include it.

Sorry, I edited the file on my MacBook and sftp'd it to my server. I changed the file on my server but forgot to commit it here. Will fix.

**Comment by saltydk** [comment]
Volumes look wrong, two container paths mounted to the same host path.

**Comment by nwithan8** [comment]
> Volumes look wrong, two container paths mounted to the same host path.

One volume expects a `config.yaml` file in it, the other will output a `Tauticord.log` file in it. Both volumes could be mapped to the same host path with no conflict.

**Comment by maximuskowalski** [comment]
`tauticord_paths_config_location: "{{ tauticord_paths_location }}/config/config.yaml"`

Would this be correct then? 
If the config dir is mapped to eg `/opt/tauticord` then config file is expected to be found at `/opt/tauticord/config/config.yml`

**Comment by saltydk** [comment]
> > Volumes look wrong, two container paths mounted to the same host path.
> 
> One volume expects a `config.yaml` file in it, the other will output a `Tauticord.log` file in it. Both volumes could be mapped to the same host path with no conflict.

Sure, I just think it is messy doing stuff like that. I'll leave that up to Max and Owine.

**Comment by saltydk** [comment]
> `tauticord_paths_config_location: "{{ tauticord_paths_location }}/config/config.yaml"`
> 
> Would this be correct then? If the config dir is mapped to eg `/opt/tauticord` then config file is expected to be found at `/opt/tauticord/config/config.yml`

The variable isn't used for anything as far as I can tell.

**Comment by nwithan8** [comment]
> `tauticord_paths_config_location: "{{ tauticord_paths_location }}/config/config.yaml"`
> 
> Would this be correct then? 
> If the config dir is mapped to eg `/opt/tauticord` then config file is expected to be found at `/opt/tauticord/config/config.yml`

My apologies, no, that would be incorrect. It's expecting to find a `config.yaml` in whatever is mapped to the `config` folder. No sub-folders. I think I was looking at the wrong spot when addressing your comment.

**Comment by benwaco** [comment]
Btw this is fixed now

**Comment by maximuskowalski** [comment]
> Will update docs if merged.

@benwaco

**Comment by maximuskowalski** [comment]
@benwaco There is someone with a problem on discord, not sure how to find you there. It looks like the config file is not being created?

> "Before using this program, you must configure it. To do this, rename the file config.yaml.example in the {{ tauticord_paths_location }}/config directory to config.yaml and edit the file to your desired settings."

**Comment by nwithan8** [comment]
> @benwaco There is someone with a problem on discord, not sure how to find you there. It looks like the config file is not being created?
> 
> > "Before using this program, you must configure it. To do this, rename the file config.yaml.example in the {{ tauticord_paths_location }}/config directory to config.yaml and edit the file to your desired settings."

This should be fixed in v3.7.0 of Tauticord: https://github.com/nwithan8/tauticord/releases/tag/v3.7.0

**Comment by maximuskowalski** [comment]
Thanks! I have not installed to check it so had mostly assumed user error.

**Pull request merged**
