### PR TITLE
feat(role): add homebox

### PR DESCRIPTION
**Pull request by JigSawFr**
# Description

Homebox is the inventory and organization system built for the Home User! With a focus on simplicity and ease of use, Homebox is the perfect solution for your home inventory, organization, and management needs. While developing this project I've tried to keep the following principles in mind:

- Simple - Homebox is designed to be simple and easy to use. No complicated setup or configuration required. Use either a single docker container, or deploy yourself by compiling the binary for your platform of choice.

- Blazingly Fast - Homebox is written in Go which makes it extremely fast and requires minimal resources to deploy. In general idle memory usage is less than 50MB for the whole container.

- Portable - Homebox is designed to be portable and run on anywhere. We use SQLite and an embedded Web UI to make it easy to deploy, use, and backup.

Demo: https://homebox.fly.dev/
Docs: https://hay-kot.github.io/homebox/

# How Has This Been Tested?

App is working (container 

- [x] App is working (container alive and answering to requests)
- [x] Secured by Authelia (API not available on front end at this time)
- [x] Ability to register an account on app
- [x] Cloudflare subdomain creation
- [x] Ability to use app as intended
- [x] Populate data in dedicated opt folder
- [x] Give tweaks infos to end user

### CODE REVIEW

**Comment by maximuskowalski** [comment]
This looks great, never even heard of it before. Just waiting on the CI...

**Comment by JigSawFr** [comment]
> This looks great, never even heard of it before. Just waiting on the CI...

Thanks max,
I like discovering new useful app ;)

**Comment by RaneyDazed** [comment]
I want it : (

**Comment by maximuskowalski** [comment]
> I want it : (

Sorry, was too tired when I got home and totally forgot.

**Pull request merged**
