### PR TITLE
Add transmissionvpn role

### PR DESCRIPTION
**Pull request by ayykamp**
# Description

Adapted from the cloudbox community role. [Container](https://hub.docker.com/r/haugene/transmission-openvpn/) and [docs](https://haugene.github.io/docker-transmission-openvpn/)

# How Has This Been Tested?

Recently migrated from cloudbox and tested on my new saltbox instance.

### CODE REVIEW

**Comment by maximuskowalski** [comment]
**I've fixed a few things**
- formatting - saltbox styling  
- credit cloudbox role author  
- added variable paths  

**Not sure about these parts**
- does it need privledged ?
- Does it need dns_servers: 8.8.8.8
And is this required in the tasks main?

```yaml
- name: "Ansible | Print a variable"
  debug:
    msg: "The operating system is {{ transmissionvpn_docker_envs_default }}"
```

Might need @saltydk to look through this one as I am not sure about the networking side of it with VPN and the way to use the extra port

`- "51413:51413"`

Checks are running now but I probably wont get back to this for a few hours at least to check. Someone else may approve it before then though. 

Thank you for the submission.

**Comment by saltydk** [comment]
I don't get notifications from pings on this repository btw. He was linked the delugevpn role as a template and I can see that the port binding is also wrong in that role. The port bindings are indeed not useful at all.

**Comment by saltydk** [comment]
I have changed my repo settings so that I will be notified now :p

**Comment by ayykamp** [comment]
- not sure if its needs priviliged, it copied that from the delugevpn role
- not sure if the dns part is needed, I didn't find a way to accomplish this with saltbox
- sorry that was from testing, I removed it in a commit

**Comment by saltydk** [comment]
I've removed the port and from a brief look at the image documentation I don't see any need for the privledge either.

**Comment by saltydk** [comment]
I didn't test anything, just fixed some bits.

**Comment by maximuskowalski** [comment]
Going to merge and rely on crowd testing for this one.

**Pull request merged**
