### PR TITLE
minecraft-bedrock: New Role

### PR DESCRIPTION
**Pull request by nickstarkloff**
# Description

The existing **minecraft** role is only for the Java version of Minecraft. This role is for the Minecraft Bedrock Edition. (the multi-platform version)

For this server you need to expose a UDP port. You can access the server via the server IP and the default port 19132.

You can create a SRV entry that maps the server IP and UDP port to a subdomain.
_Is it possible to do this automatically via Ansible?_

- [itzg/minecraft-bedrock-server](https://hub.docker.com/r/itzg/minecraft-bedrock-server)

You can select a specific server version by overwriting this variable: `minecraft_bedrock_version`

# How Has This Been Tested?

Tested on my own server.

### CODE REVIEW

**Comment by saltydk** [comment]
It is possible to create the SRV record with Ansible but we currently haven't added it as an option in our own cloudflare role.

**Comment by owine** [comment]
The `teamspeak` role sets a SRV record - perhaps it could serve as an example.

**Comment by saltydk** [comment]
> The `teamspeak` role sets a SRV record - perhaps it could serve as an example.

Ah, forgot I did that one, yeah that is a good example.

**Comment by nickstarkloff** [comment]
Thanks for the hint. Just tried to integrate it, but unfortunately it does not work.

The `teamspeak` role does not work either. Same error.

`
API bad request; Status: 400; Method: POST: Call: /zones/XXX/dns_records
`

Any ideas?

**Comment by saltydk** [comment]
Looks like the a field or two changed names, let me have a look.

**Comment by nickstarkloff** [comment]
It works now, see latest commit.

**Comment by saltydk** [comment]
I suspect yours will not work with nested subdomains.

**Comment by saltydk** [comment]
I've pushed a fix for teamspeak.

**Comment by saltydk** [comment]
The reason yours won't work with nested subdomains is that you need to set the zone to _dns_tasker_zone as that parses out the correct zone on Cloudflare.

**Comment by nickstarkloff** [comment]
Thank you! Updated the value.

The error is most likely with the module.
https://github.com/ansible-collections/community.general/issues/5167

**Comment by saltydk** [comment]
Teamspeak role used to work so must be a recent-ish change. Haven't personally used the teamspeak role since I initially made it though so no idea when.

**Comment by maximuskowalski** [comment]
Do you know if this container accepts the ENV var TZ?
```  
TZ: "{{ tz }}"
```

**Comment by nickstarkloff** [comment]
> Do you know if this container accepts the ENV var TZ?
> 
> ```
> TZ: "{{ tz }}"
> ```

The date is displayed correctly using `date`. The date in the logs provided by the server also matches the time zone.

**Comment by maximuskowalski** [comment]
OK - ready to merge then unless you have any changes planned?

> The date is displayed correctly using `date`. The date in the logs provided by the server also matches the time zone.

**Comment by nickstarkloff** [comment]
No changes planned. Ready to go. Thanks!

**Pull request merged**
