### PR TITLE
Role for PlexTraktSync

### PR DESCRIPTION
**Pull request by keldian**
Official docker image **ghcr.io/taxel/plextraktsync** with **watch** command appended so that it runs as a server and scrobbles plays. 

Library sync automation not included (maybe we can work that in later), but can be done by adding `docker exec -it plextraktsync python3 -m plextraktsync sync` to crontab, for example.

The container would not stay up without a valid Plex server to connect to, so I set the envs to login to the local Plex server by default, with override settings in _settings.yml_.

I tried my hand at customizing the tag feed with some eye-catching setup instructions, hoping they will be noticed. ¯\_(シ)_/¯

### CODE REVIEW

**Comment by maximuskowalski** [comment]
```yaml
# Envs
plextraktsync_docker_envs_default:
  TZ: "{{ tz }}"
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
```
Do these exist in the container?

**Comment by maximuskowalski** [comment]
What I am meaning is I cant see those (or any variables) mentioned in the documentation I am looking at, they may be there and given the other plex settings I expect you have found something that mentions them. If they exist then it is fine to keep them and could prevent potential problems with permissions.

**Comment by keldian** [comment]
Right. I can't confirm or deny they exist off of any official source–my findings are more trial and error based. The closest would be a comment from a maintainer that suggests PUID and GUID are unnecessary and another that suggests TZ was to be added, respectively:
https://github.com/Taxel/PlexTraktSync/issues/579#issuecomment-961960546
https://github.com/Taxel/PlexTraktSync/pull/471#discussion_r702389767

As for the Plex related envs, those are taken from the .env file that gets generated from the built-in setup guide.

I don't consider their documentation complete or up to date regarding Docker.

**Comment by maximuskowalski** [comment]
cool well lets just see what happens eh. WIll merge it after the checks run.

**Pull request merged**
