### PR TITLE
Wizarr

### PR DESCRIPTION
**Pull request by markschrik**
Wizarr is a automatic user invitation system for Plex. Create a unique link and share it to a user and they will automatically be invited to your Plex Server! They will even be guided to download the Plex client and instructions on how to use your requests software!

Automatic Invitation to your Plex Server
Secured invitation environment
Plug and Play SSO Support*
Guide user on how to download Plex client
(Optional!) Requests Integration: Guide users on how to request Movies (Overseerr, Ombi...)

# How Has This Been Tested?

- [x] This is tested on a clean SB Core install
- [x] This is testen on a used SB saltbox install

Will create docs on other pull request.

### CODE REVIEW

**Comment by maximuskowalski** [comment]
I'm not sure if these env variables are part of this container. I am only looking at the sample docker compose on the github repo so please advise if there is additional docs / info for this, otherwise I can just remove them.
```
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"
  ```

**Comment by markschrik** [comment]
I don't think those ENV's are needed. Thanks for that, need to watch that better in the future :)

**Comment by maximuskowalski** [comment]
Cool, I have removed them and made sure the auth is on for now, or would you prefer I hold off merging until you have added authelia?

**Comment by markschrik** [comment]
Hm, lets hold it for a bit. If I put it out there it might as well be right the first time :)

**Comment by markschrik** [comment]
Yes, authelia is working. Thanks! 

Will add docs later today.

**Comment by markschrik** [comment]
Documentation added https://github.com/saltyorg/docs/pull/119

**Comment by maximuskowalski** [comment]
Is this now good to go @markschrik ?

**Comment by markschrik** [comment]
Yes @maximuskowalski

**Pull request merged**
