### PR TITLE
Plex Auto Languages Role

### PR DESCRIPTION
**Pull request by hackmonker**
# Description

Role for Plex Auto Languages 

https://github.com/RemiRigal/Plex-Auto-Languages

# How Has This Been Tested?

tested in my server

### CODE REVIEW

**Comment by saltydk** [comment]
Formatting is off in a few places, I'd fix it for you but can't edit your fork.

**Comment by saltydk** [comment]
I do minor edits straight on github.com since it is quick and dirty. So not really going to do that, sorry bud. Maybe Max will do it whenever he has time.

**Comment by maximuskowalski** [comment]
I did the same thing :) will circle back and give you a PR - got a class today, maybe later or tomorrow though. Just depends how much homework I get.

**Comment by hackmonker** [comment]
added all the changes. It can be merged now I believe

**Comment by maximuskowalski** [comment]
> added all the changes. It can be merged now I believe

sorry... caught up in homework and forgot to check :)

**Pull request merged**
