### PR TITLE
Add role: Membarr

### PR DESCRIPTION
**Pull request by RaneyDazed**
# Description

Will create docs for it if it gets that far. I was hoping someone could give this a once over, as I'm struggling to figure out if I'm doing something wrong or if the bot/role itself is the problem. 

# How Has This Been Tested?

I've tested it on my home server and my feederbox. It connects fine to discord and the bot works and responds well. Everything looks good there. Only issue is it doesn't seem to want to connect to plex and I need someone or a few people to test it for me maybe? Thanks!

### CODE REVIEW

**Comment by ifelsee101** [comment]
@RaneyDazed Thanks for making this role. I was able to test this, and it works as expected after making adding 'plex_base_url = http://plex:32400' to the config.ini file. Setting up through discord channel added a weird long url to plex_base_url, I changed it to above and it worked fine.

**Comment by keldian** [comment]
Make a template for the config file. For the Plex URL, use `plex_web_url`—don't hardcode it.

 If the token can't be passed via the config file, use an env file instead of `settings.yml` (check [Watchtower](https://github.com/saltyorg/Sandbox/blob/master/roles/watchtower/defaults/main.yml) for inspiration).

**Comment by maximuskowalski** [comment]
Is a template being made for this @RaneyDazed?

**Comment by RaneyDazed** [comment]
will be messing with this in a bit! Sorry its taken so long.

**Comment by RaneyDazed** [comment]
Still working on it, about done with the template and I'll test it out on a box or two. @keldian @maximuskowalski

**Comment by RaneyDazed** [comment]
> Still working on it, about done with the template and I'll test it out on a box or two. @keldian @maximuskowalski

Well the template and subtask

**Comment by RaneyDazed** [comment]
Should be all set..?

**Comment by maximuskowalski** [comment]
Docs PR all that we need then and ready to go?

**Comment by RaneyDazed** [comment]
Yup thats correct! although i was unaware it was waiting for a Docs pr before it would be approved. I'd have done that ages ago. I just didn't want to bother if it wasn't going to be approved. But I can write up some docs!

**Comment by maximuskowalski** [comment]
Everything needs docs before it will be merged now.

**Comment by maximuskowalski** [comment]
https://github.com/saltyorg/docs/pull/205

**Pull request merged**
