### PR TITLE
fix(firefox): make the wait task less disruptive

### PR DESCRIPTION
**Pull request by keldian**

### CODE REVIEW

**Comment by keldian** [comment]
Well the idea of that task was never to stop the execution of the role, it's just to allow enough time for directories to populate, so that the next task doesn't delete the wrong ones. I don't view it as pointless as 30s should be enough time for that to happen anyway. \*shrug\*

**Comment by saltydk** [comment]
Then change the task to look for the files instead of make it silently fail if there is something wrong with the deployment

**Comment by saltydk** [comment]
You can shrug all you want, it doesn't change how it looks.

**Comment by saltydk** [comment]
This just seems to be in response to what sevos wrote on the discord and I'm betting he just deployed ufw and broke it himself.

**Comment by keldian** [comment]
I know. :p Just shrugging because I don't mind canceling this, especially if you figure if was fine as it was.

> Then change the task to look for the files instead of make it silently fail if there is something wrong with the deployment

I'll look into that at some point.

**Comment by saltydk** [comment]
Deluge role has an example from what I remember.

**Pull request closed without merging**
