### PR TITLE
Miniflux

### PR DESCRIPTION
**Pull request by powerdude**
# Description

A minimalist rss reader - http://miniflux.app

https://hub.docker.com/r/miniflux/miniflux

# How Has This Been Tested?

Tested with an existing config data from a previous ansible tool and from scratch in new SB environment

### CODE REVIEW

**Comment by owine** [comment]
Linting failed
```
[yaml[new-line-at-end-of-file]: roles/miniflux/defaults/main.yml#L161](https://github.com/saltyorg/Sandbox/pull/204/files#annotation_7217608594)
No new line character at the end of file
```

**Comment by owine** [comment]
Looks like the db user/password are circular references. I would remove the the postgres user and pass from the `vars` section when calling the postgres role and let the default user/pass be used from that role.

**Comment by powerdude** [comment]
the problem I was trying to solve with those is that I had an existing installation of miniflux and it had a different username/password for the db, so I need a way to override for this postgres db, but not for others.  Would using `lookup` in the defaults or using it in the task help?

**Comment by owine** [comment]
The way you've structured the role, a separate postgres container will be created specifically for use here.

**Comment by powerdude** [comment]
Yes, but the postgres vars are global, so changing it in the inventory affects all dbs,  so a separate var is needed for overrides and I was hoping to default it so it would just work.  Am I missing something here?

Thanks
________________________________

**Comment by owine** [comment]
I am not understanding the need to override these outside of your individual environment for testing.

But with that said, you could default `miniflux_postgres_username` and password to blank and have the `var` passed to the postgres role only if `miniflux_postgres_username`/password are populated and otherwise default to `omit`.

**Pull request merged**
