### PR TITLE
feat: add qbittorrentvpn role

### PR DESCRIPTION
**Pull request by javi11**
# Description

Add a role for qbitttorrent with VPN from https://github.com/binhex/arch-qbittorrentvpn image.

# How Has This Been Tested?

Tested by include the role in the actual sandbox and run the tag by sb install sandbox-qbittorrentvpn

- [ ] This is not a test I performed
- [ ] I did not read the paragraph above this before checking this box
- [ ] I have now checked three boxes without reading any of the text

### CODE REVIEW

**Comment by maximuskowalski** [comment]
How Has This Been Tested?

**Comment by javi11** [comment]
I add this role in my current sandbox and try the tag. Now I found some issue with the downloading of PIA json. I will fix it test it and update this :p

**Comment by javi11** [comment]
well basically you did the fixes @maximuskowalski. Thanks ;). I will add a docs pages for it

**Comment by maximuskowalski** [comment]
I have only edited formatting issues, I have not fixed the PIA issue, will wait for you to report back on that before we merge. And of course see if the CI check spits out any errors.

**Comment by javi11** [comment]
At the end was a missconfiguration. Now it works like a charm :). Let's wait for the ci

**Pull request merged**
