### PR TITLE
add ddns updater

### PR DESCRIPTION
**Pull request by hereisderek**
# Description

Lightweight universal DDNS Updater with Docker and web UI, that updates DNS A and/or AAAA records periodically for multiple DNS providers

https://github.com/qdm12/ddns-updater/
https://hub.docker.com/r/qmcgaw/ddns-updater/

# How Has This Been Tested?

Ran locally

- [ ] This is not a test I performed
- [ ] I did not read the paragraph above this before checking this box
- [ ] I have now checked three boxes without reading any of the text

### CODE REVIEW

**Comment by owine** [comment]
What's the benefit of using this over ddclient?

**Comment by hereisderek** [comment]
> What's the benefit of using this over ddclient?

it's got a pretty neat web UI, different set of supported service provider (this has 32 vs ddclient 28, based on their document.)

personally, i find ddns-updater is easier to work with ipv6 than ddclient, maybe i didn't do it right, i couldn't get both both ipv4 and ipv6 working on ddclient for the past one or two hours i was trying to set it up.

**Comment by chazlarson** [comment]
CI build is failing.

**Comment by JigSawFr** [comment]
Please also add healthcheck part (see recent PR)

**Comment by keldian** [comment]
The CI confirms what the checkboxes tell us–that you haven't tested this.

There's a way to deal with the app name having a dash without replacing it with underscore at end level or hardcoding the subdomain name. Refer to [calibre-web](https://github.com/saltyorg/Sandbox/blob/master/roles/calibre_web/defaults/main.yml) to see how it's done.

**Comment by owine** [comment]
I'm going to close this as it

a) Hasn't been tested
b) Duplicates functionality we already have with `ddclient`
c) Was created to solve a problem that we've addressed on Discord

In the future, please test roles before submitting them. The goal of Sandbox is not to be a collection of every possible app available.

**Pull request closed without merging**
