### PR TITLE
Actual Budget Role

### PR DESCRIPTION
**Pull request by Norin-Radd**
# Description

Actual Budget is a super fast and privacy-focused app for managing your finances. At its heart is the well proven and much loved Envelope Budgeting methodology.
You own your data and can do whatever you want with it. Featuring multi-device sync, optional end-to-end encryption and so much more.

https://hub.docker.com/r/actualbudget/actual-server

https://actualbudget.org/

https://actualbudget.org/docs/

I tested this through my sandbox repo and it's working and it populates my data folder after last commits.

Deleted the last part of template cause it was optional

### CODE REVIEW

**Comment by maximuskowalski** [comment]
You would need to edit [sandbox.yml](https://github.com/saltyorg/Sandbox/blob/master/sandbox.yml) to make this a role and test it properly.

Basically, switch your sandbox install to your fork, fetch and pull and switch to the branch you have used to create the role and you should be able to install like any sandbox role.

**Comment by Norin-Radd** [comment]
> You would need to edit [sandbox.yml](https://github.com/saltyorg/Sandbox/blob/master/sandbox.yml) to make this a role and test it properly.
> 
> Basically, switch your sandbox install to your fork, fetch and pull and switch to the branch you have used to create the role and you should be able to install like any sandbox role.

I'm sorry, but I'll need further instructions on how to do that via Discord. I tried to follow the documents, but I couldn't get there.

**Comment by Norin-Radd** [comment]
> You would need to edit [sandbox.yml](https://github.com/saltyorg/Sandbox/blob/master/sandbox.yml) to make this a role and test it properly.
> 
> Basically, switch your sandbox install to your fork, fetch and pull and switch to the branch you have used to create the role and you should be able to install like any sandbox role.

Hello, thanks for the help.

I already tested it on my server running saltbox, please feel free to test further and evaluate the pull request.

**Comment by maximuskowalski** [comment]
Looking at the recommended compose it looks like your config location
`- "{{ actualbudget_paths_location }}:/opt/data"`
Should actually be
`- "{{ actualbudget_paths_location }}:/data"`

Which then uses the sub folders `/data/server-files` and `/data/user-files`

It looks like the config file if supplied is meant to be `config.json` which means this is likely wrong if you are trying to supply a config file but I can't see any pre-config happening anyway.:
`actualbudget_config_location: "{{ actualbudget_paths_location }}/configuration.yaml"`

It doesn't appear that this ENV var is required:
`  - "/run/udev:/run/udev:ro"`
There are ENV options listed here https://actualbudget.org/docs/config/

### You will also need to supply the link to your DOCS PR before this will be accepted.

Did the Pull Request template fail to populate when you made it?
You should have seen something like this:
https://github.com/saltyorg/Sandbox/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Norin-Radd** [comment]
https://github.com/saltyorg/docs/pull/323

Docs pull request link

**Pull request merged**
