### PR TITLE
Add Full Text Rss

### PR DESCRIPTION
**Pull request by RaneyDazed**
# Description

Creating this as a draft because I think Max intended to help me with it? The web ui pulls up just fine, The admin panel works fine as well. But there are some apparent issues with php or apache? It also passes the "Compatability test" as well. Which is fulltextrss.domain.tld/compatability_test.php. It won't download the massive list of config files though. 

I'd test the rss functions if I knew how to. 

# How Has This Been Tested?

- [x] Tested as saltbox_mod role on local server
- [x] Tested as saltbox_mod role on hetzner server.

### CODE REVIEW

**Comment by RaneyDazed** [comment]
Reference: #185

**Comment by RaneyDazed** [comment]
docker envs from `docker inspect fulltextrss`
```yaml
            "Env": [
                "FTR_ADMIN_PASSWORD=REDACTED",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "APACHE_CONFDIR=/etc/apache2",
                "APACHE_ENVVARS=/etc/apache2/envvars",
                "PHP_EXTRA_BUILD_DEPS=apache2-dev",
                "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2 --disable-cgi",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2",
                "PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie",
                "GPG_KEYS=REDACTED JUST IN CASE",
                "PHP_VERSION=5.6.40",
                "PHP_URL=https:/ALSO REDACTED",
                "PHP_ASC_URL=https://secure.php.net/get/php-5.6.40.tar.xz.asc/from/this/mirror",
                "PHP_SHA256=REDACTED. AFTER ALL, WHY SHOULDN'T I",
                "PHP_MD5="
```
I did try to create an RSS feed from medium.com. It failed. Nothing in the role directory either. I def did something wrong

**Comment by maximuskowalski** [comment]
I tried on a non saltbox local setup - there is some problem with the volume - if I leave out the mapping of `:/var/www/html/cache" then it works on my local setup. If I include it I get an error.

Have not had much time lately sorry Chair.

**Comment by RaneyDazed** [comment]
> I tried on a non saltbox local setup - there is some problem with the volume - if I leave out the mapping of `:/var/www/html/cache" then it works on my local setup. If I include it I get an error.
> 
> Have not had much time lately sorry Chair.

No worries man! Like you guys tell me all the time, no rush! I'll take another look at it tomorrow, or maybe Friday since the kids have wrestling practice tomorrow night. : )

**Comment by saltydk** [comment]
I have no idea how to test this weird thing, so give my edit a go in a fresh install.

**Comment by saltydk** [comment]
CI was fine, I just used it for something afterwards.

**Comment by maximuskowalski** [comment]
Made a small change and it now "works" but with authelia in front you cant connect the generated clean feeds to an RSS reader. 

By changing the subscription link to http://dockerlink you can get around it
Example:
`https://fulltextrss._MYDOMAIN_._COM_/makefulltextfeed.php?url=feeds.bbci.co.uk%2Fnews%2Fworld%2Frss.xml&max=200&links=preserve&exc=`
will work as
`http://fulltextrss/makefulltextfeed.php?url=feeds.bbci.co.uk%2Fnews%2Fworld%2Frss.xml&max=200&links=preserve&exc=`

But that is only within the docker network obviously. There is an option to enable an API key and whitelist a domain but I think we might need to make our own docker image to achieve this. Xmas day so I am not going to read any more on this one today. Might be one to look at after the jump or place in the sandpit.

**Pull request closed without merging**
